### ISSUE TITLE
能否支持一下babel编译，发现在iOS6旧系统中无法支持...扩展？

### ISSUE THREAD

**Issue by 921010wxm** [tony801015/chinese-lunar#16]
能否支持一下babel编译，发现在iOS6旧系统中无法支持...扩展？

**Comment by tony801015** [comment]
> 能否支持一下babel编译，发现在iOS6旧系统中无法支持...扩展？

感謝您的回覆，我在安排一下或是歡迎你發Pull request唷~

**Comment by tony801015** [comment]
@921010wxm 可以幫我測試一下這個版本嗎？
https://github.com/tony801015/chinese-lunar/tree/fix_ios6_issue
`@tony801015/chinese-lunar@0.19.0-beta`
