### ISSUE TITLE
名字评分，运势评分

### ISSUE THREAD

**Issue by yxyufo110** [tony801015/chinese-lunar#18]
想请教下设计思路

**Comment by yxyufo110** [comment]
是的，看了一些sdk都是爬虫类的，想自己做一个，不知道从哪方面下手

**Comment by tony801015** [comment]
> 是的，看了一些sdk都是爬虫类的，想自己做一个，不知道从哪方面下手

這個需要一些命理學的domain know-how才有機會自己做一個，也比較能優化有價值，不然真的只能用別人的sdk了

**Comment by yxyufo110** [comment]
多谢啦。close

**Comment by tony801015** [comment]
@yxyufo110 不用客氣。也歡迎Mail討論唷。
